### ISSUE TITLE
Rover only seems to run in caf-terraform-landingzones

### ISSUE THREAD

**Issue by Justin-DynamicD** [aztfmod/rover#75]
So I want ot expand on the landingzone example in the caf-terraform-landingzones prject, but I cant seem to run this container "outside" of it.

Example, if I clone this repo and simply open it I get errors when it tries to launch the container:

```
Start: Run in container: cd /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69; export VSCODE_AGENT_FOLDER=/home/vscode/.vscode-server; /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh --extensions-download-dir /home/vscode/.vscode-server/extensionsCache --install-extension 4ops.terraform --install-extension mutantdino.resourcemonitor --install-extension eamodio.gitlens --force
[8828 ms] Remote-Containers server: events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied /home/vscode/.gnupg/S.gpg-agent
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1453:5)
    at internal/util.js:278:30
    at new Promise (<anonymous>)
    at bound  (internal/util.js:277:12)
    at /tmp/vscode-remote-containers-server-fa0151898feb4380a1b0e4d8aebc2a0f76250387.js:1:30280
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1333:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '/home/vscode/.gnupg/S.gpg-agent',
  port: -1
}
[8876 ms] Remote-Containers server terminated (code: 1, signal: null).
```

The container then hangs on installing extensions and fails to ever get to a state where I have bash access.

If i run the same .devcontainer contents in the caf-terraform-landingzones project, everything loads fine.

Is the container expecting a specific project layout? If I wantto split my landingzones into multiple repos with a custom layout ... does this fail to acocunt for that?

**Comment by Justin-DynamicD** [comment]
just adding that simply renaming the project folder name to "caf-terraform-landingzones" lets the container load.  This basically forces me to keep that project name, even if I want to completely change the contents/structure

**Comment by arnaudlh** [comment]
hi @Justin-DynamicD , this is not the intended behavior, let me investigate - what version of vscode are you running?

**Comment by Justin-DynamicD** [comment]
Good question. Validating I seem to be running:

VSCode: 1.49.3
docker engine: 19.03.13 (with wsl2 enabled)
rover: just cloning/spinning up from master

I just repulled to verify and get the same error, but on closer reading there might be some kind of conflict with my locally installed extensions?

```
[7756 ms] Start: Run in container: /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/server.sh --disable-user-env-probe --use-host-proxy --port 0 --extensions-download-dir /home/vscode/.vscode-server/extensionsCache
[8488 ms] Remote-Containers server: events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied /home/vscode/.gnupg/S.gpg-agent
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1453:5)
    at internal/util.js:278:30
    at new Promise (<anonymous>)
    at bound  (internal/util.js:277:12)
    at /tmp/vscode-remote-containers-server-f57e52451ecf6a87c51264cf9ec5b13b4211df55.js:1:30280
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1333:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '/home/vscode/.gnupg/S.gpg-agent',
  port: -1
}
[8543 ms] Error: stream ended with:0 but wanted:9
        at p (c:\Users\justi\.vscode\extensions\ms-vscode-remote.remote-containers-0.140.1\dist\extension.js:1:215920)
        at c:\Users\justi\.vscode\extensions\ms-vscode-remote.remote-containers-0.140.1\dist\extension.js:1:216090
        at s (c:\Users\justi\.vscode\extensions\ms-vscode-remote.remote-containers-0.140.1\dist\extension.js:1:231407)
        at Socket.<anonymous> (c:\Users\justi\.vscode\extensions\ms-vscode-remote.remote-containers-0.140.1\dist\extension.js:1:231580)
        at Socket.emit (events.js:228:7)
        at endReadableNT (_stream_readable.js:1185:12)
        at processTicksAndRejections (internal/process/task_queues.js:81:21)
[8544 ms] Remote-Containers server terminated (code: 1, signal: null).
```
It looks like its trying to read my locally installed extensions?  I'm honestly just not sure what the rover is trying to pull off at this step

**Comment by Justin-DynamicD** [comment]
As an FYI I can (and do) run my own custom containers for clients and myself basically all day (I make a unique container per client), so the base remote-container extension appears to work just fine.

**Comment by Justin-DynamicD** [comment]
So with some serious gymnastics it looks like i can get it running. So to be completely sure of things I:

1. cleared all containers
2. cleared all volumes
3. cleared all images 
4. removed all extensions  from installing from devcontainer.json
5. reopened in container ...

Here's the full log:

```
Status: Downloaded newer image for aztfmod/roverdev:vnext
Creating rover_devcontainer_rover_1 ... done
[74851 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=rover_devcontainer --filter label=com.docker.compose.service=rover
[75314 ms] Start: Run: docker inspect --type container 5463d09eb9bd
[75985 ms] Start: Inspecting container
[75985 ms] Start: Run: docker inspect --type container 5463d09eb9bd4fcd1c21b113194d3d41a2253daedb3e5da90254c8378e518e76
[76416 ms] Start: Run: docker exec -i -u vscode -e VSCODE_REMOTE_CONTAINERS_SESSION=cd00ae4e-ea1d-4bf5-9091-fcab6fcaab9d1602291520290 5463d09eb9bd4fcd1c21b113194d3d41a2253daedb3e5da90254c8378e518e76 /bin/sh
[76430 ms] Start: Run in container: uname -m
[76877 ms] x86_64
[76877 ms] 
[76877 ms] Start: Run in container: (cat /etc/os-release || cat /usr/lib/os-release) 2>/dev/null
[76892 ms] NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[76892 ms] 
[76892 ms] Start: Run in container: cat /etc/passwd
[76896 ms] Start: Updating configuration state
[76903 ms] Start: Setup shutdown monitor
[76907 ms] Forking shutdown monitor: c:\Users\justi\.vscode\extensions\ms-vscode-remote.remote-containers-0.140.1\dist\shutdownMonitorProcess \\.\pipe\vscode-remote-containers-40a5c73652ffec1a46a66cf37ee528ba7f475dd0-sock dockerCompose Info c:\Users\justi\AppData\Roaming\Code\logs\20201009T175830\exthost1\ms-vscode-remote.remote-containers
[76919 ms] Start: Run in container: test -d /home/vscode/.vscode-server
[76927 ms] 
[76928 ms] 
[76930 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[76944 ms] 
[76944 ms] 
[76945 ms] Start: Run in container: mkdir -p '/home/vscode/.vscode-server/data/Machine' && cat >'/home/vscode/.vscode-server/data/Machine/settings.json' <<'settingsJSON'
[76952 ms] 
[76953 ms] 
[76954 ms] Start: Run in container: test -d /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69
[76959 ms] 
[76959 ms] 
[76959 ms] Exit code 1
[76960 ms] Installing VS Code Server for commit 2af051012b66169dde0c4dfae3f5ef48f787ff69
[76960 ms] Start: Run in container: mkdir -p /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69_1602291598292
[76966 ms] 
[76966 ms] 
[77001 ms] Start: Run in container: (dd iflag=fullblock bs=8192 count=3918 2>/dev/null; dd iflag=fullblock bs=7900 count=1 2>/dev/null) | tar --no-same-owner -xz --strip-components 1 -C /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69_1602291598292
[78127 ms] 
[78127 ms] 
[78127 ms] Start: Run in container: mv -n /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69_1602291598292 /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69
[78131 ms] 
[78131 ms] 
[78131 ms] Start: Launching Remote-Containers helper.
[78131 ms] Start: Run: gpgconf --list-dir agent-extra-socket
[78196 ms] Start: Run in container: gpgconf --list-dir agent-socket
[78200 ms] sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/libexec
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
dirmngr-socket:/var/run/dirmngr/socket
agent-socket:/home/vscode/.gnupg/S.gpg-agent
homedir:/home/vscode/.gnupg
[78200 ms] 
[78200 ms] Start: Run in container: gpgconf --list-dir homedir
[78203 ms] sysconfdir:/etc/gnupg
bindir:/usr/bin
libexecdir:/usr/libexec
libdir:/usr/lib64/gnupg
datadir:/usr/share/gnupg
localedir:/usr/share/locale
dirmngr-socket:/var/run/dirmngr/socket
agent-socket:/home/vscode/.gnupg/S.gpg-agent
homedir:/home/vscode/.gnupg
[78203 ms] 
[78203 ms] Start: Run in container: ls '/home/vscode/.gnupg/private-keys-v1.d' 2>/dev/null
[78208 ms] 
[78208 ms] 
[78208 ms] Exit code 2
[78208 ms] Start: Run in container: mkdir -p -m 700 '/home/vscode/.gnupg'
[78212 ms] 
[78212 ms] mkdir: cannot create directory '/home/vscode/.gnupg': Permission denied
[78212 ms] Exit code 1
[78212 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-6e5afa4db146847115b1fb7dfea72feb886f4e4f.js' >/tmp/vscode-remote-containers-6e5afa4db146847115b1fb7dfea72feb886f4e4f.js
[78218 ms] 
[78218 ms] 
[78218 ms] Start: Run in container: # Test for /home/vscode/.gitconfig and git
[78223 ms] 
[78223 ms] 
[78224 ms] Start: Run in container: cat <<'EOF-/tmp/vscode-remote-containers-server-6e5afa4db146847115b1fb7dfea72feb886f4e4f.js' >/tmp/vscode-remote-containers-server-6e5afa4db146847115b1fb7dfea72feb886f4e4f.js
[78260 ms] 
[78260 ms] 
[78260 ms] Start: Run in container: # Copy C:\Users\justi\.gitconfig to /home/vscode/.gitconfig
[78260 ms] Start: Run: docker exec -i -u vscode -e REMOTE_CONTAINERS_SOCKETS=["/tmp/vscode-ssh-auth-6e5afa4db146847115b1fb7dfea72feb886f4e4f.sock","/home/vscode/.gnupg/S.gpg-agent"] -e REMOTE_CONTAINERS_IPC=/tmp/vscode-remote-containers-ipc-6e5afa4db146847115b1fb7dfea72feb886f4e4f.sock 5463d09eb9bd4fcd1c21b113194d3d41a2253daedb3e5da90254c8378e518e76 /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/node /tmp/vscode-remote-containers-server-6e5afa4db146847115b1fb7dfea72feb886f4e4f.js
[78263 ms] 
[78263 ms] /bin/sh: line 38: /home/vscode/.gitconfig: Permission denied
[78263 ms] Exit code 1
[78263 ms] Start: Run in container: command -v git >/dev/null 2>&1 && git config --global credential.helper '!f() { /home/vscode/.vscode-server/bin/2af051012b66169dde0c4dfae3f5ef48f787ff69/node /tmp/vscode-remote-containers-6e5afa4db146847115b1fb7dfea72feb886f4e4f.js $*; }; f' || true
[78301 ms] 
[78301 ms] /bin/sh: line 39: [user]: command not found
/bin/sh: line 40: name: command not found
/bin/sh: line 41: email: command not found
/bin/sh: line 42: [core]: command not found
/bin/sh: line 43: autocrlf: command not found
/bin/sh: line 44: [credential]: command not found
/bin/sh: line 45: helper: command not found
/bin/sh: line 46: [filter: command not found
/bin/sh: line 47: clean: command not found
/bin/sh: line 48: smudge: command not found
/bin/sh: line 49: process: command not found
/bin/sh: line 50: required: command not found
error: could not lock config file /home/vscode/.gitconfig: Permission denied
[78302 ms] Start: Run in container: # Test for /home/vscode/.ssh/known_hosts and ssh
[78308 ms] 
[78308 ms] 
[78308 ms] Start: Run in container: # Copy C:\Users\justi\.ssh\known_hosts to /home/vscode/.ssh/known_hosts
[78314 ms] 
[78315 ms] 
[78315 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.installExtensionsMarker' ; } 2> /dev/null
[78320 ms] 
[78320 ms] 
[78322 ms] Start: Run in container: set -o noclobber ; mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.postCreateCommandMarker' ; } 2> /dev/null
[78329 ms] 
[78329 ms] 
[78329 ms] Start: Run in container: test -f /home/vscode/.vscode-server/.postCreateCommandMarker
[78332 ms] 
[78332 ms] 
[78332 ms] Exit code 1
[78750 ms] Remote-Containers server: events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied /home/vscode/.gnupg/S.gpg-agent
    at Server.setupListenHandle [as _listen2] (net.js:1289:21)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1453:5)
    at internal/util.js:278:30
    at new Promise (<anonymous>)
    at bound  (internal/util.js:277:12)
    at /tmp/vscode-remote-containers-server-6e5afa4db146847115b1fb7dfea72feb886f4e4f.js:1:30280
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1333:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '/home/vscode/.gnupg/S.gpg-agent',
  port: -1
}
[78817 ms] Remote-Containers server terminated (code: 1, signal: null)
```

**Comment by Justin-DynamicD** [comment]
well in frustration I give up. Ive now stepped backwards in that I cant get any verion of the rover to run under any circumstance. Ive tried 3 different tags, the roverdev, and even the roveralpha.  They all die. I even tried to `docker-compose build ` and it fails to build.

I agree the folder srtructure shuldnt matter, its just a mount path.  but near as I can tell, this complex series of startup scripts is imploding. I mrunning insider beta channel ... is it possible somethign broke fundamentally with WSL2 there?  Maybe ... but at this point this seems like a bootstrap mess.

I really hope you guys maybe just make a wrapper in go that is a one-file copy that does the work and we can just drop it in any container we want ... becuase this feels unworkable.

**Comment by arnaudlh** [comment]
hi @Justin-DynamicD thanks for your feedback, we found a bug in the rover building process that was causing this access denied and you can aztfmod/roverdev:2010.141511. 

Simplest way to test it is to use the .devcontainer from https://github.com/aztfmod/terraform-azurerm-caf/tree/0.4/.devcontainer, delete the docker volumes and rebuild the container in vscode.

Let us know if that works or you see the problem happening again.

Thanks
Arnaud
